# Generated by Django 5.1.3 on 2024-12-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_average_rating_post_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ema_rating',
            field=models.FloatField(default=0),
        ),
    ]
